// Copyright @filterpaper
// SPDX-License-Identifier: GPL-2.0+

#pragma once

// Common QMK settings
#define TAP_CODE_DELAY 5
#define TAP_HOLD_CAPS_DELAY 35
#define USB_SUSPEND_WAKEUP_DELAY 500
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

//  Tap-hold settings
#define TAPPING_TERM 250
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM_PER_KEY

#ifdef POINTING_DEVICE_ENABLE
#  define MEDIA_TAP_THRESHOLD 85
#  define MEDIA_TAP_TERM 600
// Auto mouse config
#  define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#  ifdef POINTING_DEVICE_AUTO_MOUSE_ENABLE
#    define AUTO_MOUSE_DEFAULT_LAYER MOU
#    define AUTO_MOUSE_TIME 600
#    define AUTO_MOUSE_DEBOUNCE 50
// #    define AUTO_MOUSE_DELAY 1000
#    define AUTO_MOUSE_THRESHOLD 10
#  endif
#  ifndef CARRET_TIMEOUT_MS
#    define CARRET_TIMEOUT_MS 150
#  endif
#  ifndef MEDIA_TIMEOUT_MS
#    define MEDIA_TIMEOUT_MS 50
#  endif
#endif

#ifdef KEYBOARD_charybdis
/* Trackball angle adjustment. */
#  ifdef ROTATIONAL_TRANSFORM_ANGLE
#    undef ROTATIONAL_TRANSFORM_ANGLE
#  endif

#  define ROTATIONAL_TRANSFORM_ANGLE -32
#endif

#ifdef KEYBOARD_tenome
#  define TENOME_ENCODER_LEDS

#  ifdef TRACKBALL_ENABLE
#    ifdef ROTATIONAL_TRANSFORM_ANGLE
#      undef ROTATIONAL_TRANSFORM_ANGLE
#    endif

#    define ROTATIONAL_TRANSFORM_ANGLE -28
#  else
// #    define POINTING_DEVICE_GESTURES_SCROLL_ENABLE // Circular scroll.
#    define CIRQUE_PINNACLE_TAP_ENABLE
// absolute mode
// #  undef CIRQUE_PINNACLE_POSITION_MODE
// #  define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_RELATIVE_MODE
// #  ifdef CIRQUE_PINNACLE_ABSOLUTE_MODE
#    define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#    define CIRQUE_PINNACLE_TAPPING_TERM 100
#    define CIRQUE_PINNACLE_TOUCH_DEBOUNCE 250
#    define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_2X
#  endif
#endif

#ifdef KEYBOARD_buteo
// #    define POINTING_DEVICE_GESTURES_SCROLL_ENABLE // Circular scroll.
#  define CIRQUE_PINNACLE_TAP_ENABLE
// #  define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE
// absolute mode
// #  undef CIRQUE_PINNACLE_POSITION_MODE
// #  define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_RELATIVE_MODE
// #  ifdef CIRQUE_PINNACLE_ABSOLUTE_MODE
#  define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#  define CIRQUE_PINNACLE_TAPPING_TERM 110
#  define CIRQUE_PINNACLE_TOUCH_DEBOUNCE 250
#  define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_2X
#endif

#ifdef KEYBOARD_buteo_talon
#  define AZOTEQ_IQS5XX_SCROLL_INITIAL_DISTANCE 15
#  define AZOTEQ_IQS5XX_PRESS_AND_HOLD_ENABLE true
#  define AZOTEQ_IQS5XX_HOLD_TIME 250
// #  define AZOTEQ_IQS5XX_SWIPE_X_ENABLE true
// #  define AZOTEQ_IQS5XX_SWIPE_Y_ENABLE true
// #  define AZOTEQ_IQS5XX_SWIPE_INITIAL_TIME 350
// #  define AZOTEQ_IQS5XX_SWIPE_INITIAL_DISTANCE 1000
#  define AZOTEQ_IQS5XX_ZOOM_ENABLE true
#  define AZOTEQ_IQS5XX_ZOOM_INITIAL_DISTANCE 450
#endif

// Tripple tapping a OSM will lock it until it's pressed again
#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 5000

#ifdef COMBO_ENABLE
#  ifdef COMBO_TERM
#    undef COMBO_TERM
#  endif
#  define COMBO_TERM 50
#  define COMBO_MUST_HOLD_PER_COMBO
#  define COMBO_MUST_TAP_PER_COMBO
#  define COMBO_TERM_PER_COMBO
#  define COMBO_SHOULD_TRIGGER
// #  define COMBO_ONLY_FROM_LAYER 0
#endif

#ifdef MOUSEKEY_ENABLE
#  define MOUSEKEY_DELAY 0      // Delay between pressing a key and cursor movement
#  define MOUSEKEY_INTERVAL 15  // Time between cursor movements in milliseconds
#  define MOUSEKEY_MOVE_DELTA 8 // Step size for acceleration
#  define MOUSEKEY_MAX_SPEED 3
#  define MOUSEKEY_TIME_TO_MAX 80
#  define MOUSEKEY_WHEEL_DELAY 16
#  define MOUSEKEY_WHEEL_INTERVAL 30
#  define MOUSEKEY_WHEEL_MAX_SPEED 3
#  define MOUSEKEY_WHEEL_TIME_TO_MAX 95
#endif

// Add hires scroll support
#ifdef TRACKBALL_ENABLE
# define POINTING_DEVICE_HIRES_SCROLL_ENABLE
# define POINTING_DEVICE_HIRES_SCROLL_MULTIPLIER 50
# define POINTING_DEVICE_HIRES_SCROLL_EXPONENT 100
# define WHEEL_EXTENDED_REPORT
#endif

// Layout macros
#ifndef __ASSEMBLER__
#  include "layout.h"
#endif
